//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCSharp.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DiagnosticStringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiagnosticStringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCSharp.Analyzers.DiagnosticStringResources", typeof(DiagnosticStringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PartSolutionAttribute may only be applied on methods that solve a problem part, annotated with PartSolverAttribute.
        /// </summary>
        internal static string AoCS0001_MessageFormat {
            get {
                return ResourceManager.GetString("AoCS0001_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PartSolutionAttribute on non-solution method.
        /// </summary>
        internal static string AoCS0001_Title {
            get {
                return ResourceManager.GetString("AoCS0001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PartSolutionStatus value provided on the PartSolutionAttribute must be a declared enum value.
        /// </summary>
        internal static string AoCS0002_MessageFormat {
            get {
                return ResourceManager.GetString("AoCS0002_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PartSolutionStatus value on PartSolutionAttribute.
        /// </summary>
        internal static string AoCS0002_Title {
            get {
                return ResourceManager.GetString("AoCS0002_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer using Problem&lt;T&gt; for problems whose both parts have the same return type.
        /// </summary>
        internal static string AoCS0003_MessageFormat {
            get {
                return ResourceManager.GetString("AoCS0003_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer using Problem&lt;T&gt; for problems whose both parts have the same return type.
        /// </summary>
        internal static string AoCS0003_Title {
            get {
                return ResourceManager.GetString("AoCS0003_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem solution classes should be contained in namespaces denoting the year of the problem.
        /// </summary>
        internal static string AoCS0004_MessageFormat {
            get {
                return ResourceManager.GetString("AoCS0004_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Containing namespace of a problem solution class must end in &apos;Year20XX&apos;.
        /// </summary>
        internal static string AoCS0004_Title {
            get {
                return ResourceManager.GetString("AoCS0004_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denoted problem year must be a valid year after 2015, up until the current one.
        /// </summary>
        internal static string AoCS0005_MessageFormat {
            get {
                return ResourceManager.GetString("AoCS0005_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The denoted year should be a valid year.
        /// </summary>
        internal static string AoCS0005_Title {
            get {
                return ResourceManager.GetString("AoCS0005_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem solution classes should be named appropriately to denote the day of the problem.
        /// </summary>
        internal static string AoCS0006_MessageFormat {
            get {
                return ResourceManager.GetString("AoCS0006_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem solution class must be named &apos;DayX&apos;.
        /// </summary>
        internal static string AoCS0006_Title {
            get {
                return ResourceManager.GetString("AoCS0006_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denoted problem day must be between 1 and 25.
        /// </summary>
        internal static string AoCS0007_MessageFormat {
            get {
                return ResourceManager.GetString("AoCS0007_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denoted problem day must be between 1 and 25.
        /// </summary>
        internal static string AoCS0007_Title {
            get {
                return ResourceManager.GetString("AoCS0007_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SecretsContainerAttribute can only be used on a sealed class that inherits ISecretsContainer and provides a public parameterless constructor.
        /// </summary>
        internal static string AoCS0008_MessageFormat {
            get {
                return ResourceManager.GetString("AoCS0008_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SecretsContainerAttribute on non-secret container class.
        /// </summary>
        internal static string AoCS0008_Title {
            get {
                return ResourceManager.GetString("AoCS0008_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinalDay&lt;T&gt; contains additional abstracted logic specialized for Day 25 problems.
        /// </summary>
        internal static string AoCS0011_MessageFormat {
            get {
                return ResourceManager.GetString("AoCS0011_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer inheriting FinalDay&lt;T&gt; for Day 25 solutions.
        /// </summary>
        internal static string AoCS0011_Title {
            get {
                return ResourceManager.GetString("AoCS0011_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinalDay&lt;T&gt; is specialized for Day 25 problems.
        /// </summary>
        internal static string AoCS0012_MessageFormat {
            get {
                return ResourceManager.GetString("AoCS0012_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only use FinalDay&lt;T&gt; for Day 25 problems.
        /// </summary>
        internal static string AoCS0012_Title {
            get {
                return ResourceManager.GetString("AoCS0012_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartSolverAttribute should only be placed on public instance methods with no parameters or generic parameters with a non-void return type in a problem solution class.
        /// </summary>
        internal static string AoCS0013_MessageFormat {
            get {
                return ResourceManager.GetString("AoCS0013_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PartSolverAttribute on non-solver method.
        /// </summary>
        internal static string AoCS0013_Title {
            get {
                return ResourceManager.GetString("AoCS0013_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name has already been used for a part solver in this solution class.
        /// </summary>
        internal static string AoCS0014_MessageFormat {
            get {
                return ResourceManager.GetString("AoCS0014_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate part name in the same solution class.
        /// </summary>
        internal static string AoCS0014_Title {
            get {
                return ResourceManager.GetString("AoCS0014_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The part name exceeds the 20-character limit, with the excessive characters being trimmed.
        /// </summary>
        internal static string AoCS0015_MessageFormat {
            get {
                return ResourceManager.GetString("AoCS0015_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit part names to 20 characters max.
        /// </summary>
        internal static string AoCS0015_Title {
            get {
                return ResourceManager.GetString("AoCS0015_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer string converters should always declare the type of objects they&apos;re converting.
        /// </summary>
        internal static string AoCS0016_MessageFormat {
            get {
                return ResourceManager.GetString("AoCS0016_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not directly inherit AnswerStringConverter.
        /// </summary>
        internal static string AoCS0016_Title {
            get {
                return ResourceManager.GetString("AoCS0016_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Further restrict the objects that can be converted by an answer string converter.
        /// </summary>
        internal static string AoCS0017_MessageFormat {
            get {
                return ResourceManager.GetString("AoCS0017_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not declare object answer string converters.
        /// </summary>
        internal static string AoCS0017_Title {
            get {
                return ResourceManager.GetString("AoCS0017_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primitive type &apos;{0}&apos; is by default handled by CommonAnswerStringConverter.
        /// </summary>
        internal static string AoCS0018_MessageFormat {
            get {
                return ResourceManager.GetString("AoCS0018_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some primitive types are handled by the framework.
        /// </summary>
        internal static string AoCS0018_Title {
            get {
                return ResourceManager.GetString("AoCS0018_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; {1} does not match the target pattern, please ensure the entire string is used.
        /// </summary>
        internal static string AoCS0080_MessageFormat {
            get {
                return ResourceManager.GetString("AoCS0080_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret string does not match the pattern.
        /// </summary>
        internal static string AoCS0080_Title {
            get {
                return ResourceManager.GetString("AoCS0080_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A non-abstract type that inherits ISecretsContainer should contain properties with the SecretStringPropertyAttribute.
        /// </summary>
        internal static string AoCS0081_MessageFormat {
            get {
                return ResourceManager.GetString("AoCS0081_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type inheriting ISecretsContainer does not contain any secret string properties.
        /// </summary>
        internal static string AoCS0081_Title {
            get {
                return ResourceManager.GetString("AoCS0081_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is better practice to use a constant field for the type of the secret string.
        /// </summary>
        internal static string AoCS0082_MessageFormat {
            get {
                return ResourceManager.GetString("AoCS0082_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer using a constant field for the type of the secret string.
        /// </summary>
        internal static string AoCS0082_Title {
            get {
                return ResourceManager.GetString("AoCS0082_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerical types are not valid for secret string properties.
        /// </summary>
        internal static string AoCS0083_MessageFormat {
            get {
                return ResourceManager.GetString("AoCS0083_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only types inheriting ISecretsContainer should contain properties with the SecretStringPropertyAttribute.
        /// </summary>
        internal static string AoCS0084_MessageFormat {
            get {
                return ResourceManager.GetString("AoCS0084_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proprties marked with SecretStringPropertyAttribute must be contained in a type inheriting ISecretsContainer.
        /// </summary>
        internal static string AoCS0084_Title {
            get {
                return ResourceManager.GetString("AoCS0084_Title", resourceCulture);
            }
        }
    }
}
